[package]
name = "vnode"
version = "0.1.0"
edition = "2021"

[dependencies]
library = { path = "../library" }
lnxparser = { git = "https://github.com/brown-csci1680/ipstack-utils" }
rustyline = "14.0.0"
