[package]
name = "library"
version = "0.1.0"
edition = "2021"

[dependencies]
etherparse = "0.16"
ipnet = "2.10.1"
prettyprint = "0.8.1"
rustyline = "14.0.0"
lnxparser = { git = "https://github.com/brown-csci1680/ipstack-utils" }